env: "local" # local, dev, prod and so on
storage_path: "../storage/storage.db"
http_server:
  address: "localhost:8085"
  timeout: 4s # time for receiving request and sendig the response. time for request processing doesn't include here
  idle_timeout: 60s